server:
  port: 10086
spring:
  application:
    name: jz-registry # spring.application.name 作为服务间相互调用的服务名
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启Spring Cloud的重试功能
serviceName:
  ribbon:
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
eureka:
  client:
    service-url:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms